const emojiList = [
    { char: '😀', names: ['grinning', 'smile', 'happy'] },
    { char: '😃', names: ['smiley', 'smile', 'happy'] },
    { char: '😄', names: ['smile', 'happy', 'laugh'] },
    { char: '😁', names: ['grin', 'smile', 'happy'] },
    { char: '😆', names: ['laughing', 'satisfied', 'lol'] },
    { char: '😅', names: ['sweat_smile', 'hot', 'relief'] },
    { char: '🤣', names: ['rofl', 'lol', 'laughing'] },
    { char: '😂', names: ['joy', 'tears', 'cry', 'lol'] },
    { char: '🙂', names: ['slightly_smiling_face', 'smile'] },
    { char: '🙃', names: ['upside_down_face', 'silly'] },
    { char: '😉', names: ['wink', 'flirt'] },
    { char: '😊', names: ['blush', 'smile', 'happy'] },
    { char: '😇', names: ['innocent', 'angel'] },
    { char: '🥰', names: ['smiling_face_with_3_hearts', 'love'] },
    { char: '😍', names: ['heart_eyes', 'love', 'crush'] },
    { char: '🤩', names: ['star_struck', 'eyes'] },
    { char: '😘', names: ['kissing_heart', 'flirt'] },
    { char: '😗', names: ['kissing'] },
    { char: '☺️', names: ['relaxed', 'blush'] },
    { char: '😚', names: ['kissing_closed_eyes'] },
    { char: '😙', names: ['kissing_smiling_eyes'] },
    { char: '😋', names: ['yum', 'tongue', 'licks'] },
    { char: '😛', names: ['stuck_out_tongue'] },
    { char: '😜', names: ['stuck_out_tongue_winking_eye', 'prank', 'silly'] },
    { char: '🤪', names: ['zany_face', 'goofy', 'wacky'] },
    { char: '😝', names: ['stuck_out_tongue_closed_eyes', 'prank'] },
    { char: '🤑', names: ['money_mouth_face', 'rich'] },
    { char: '🤗', names: ['hugs'] },
    { char: '🤭', names: ['hand_over_mouth', 'quiet', 'oops'] },
    { char: '🤫', names: ['shushing_face', 'silence', 'secret'] },
    { char: '🤔', names: ['thinking', 'hmm'] },
    { char: '🤐', names: ['zipper_mouth_face', 'silence', 'secret'] },
    { char: '🤨', names: ['raised_eyebrow', 'suspicious'] },
    { char: '😐', names: ['neutral_face', 'meh'] },
    { char: '😑', names: ['expressionless', 'meh'] },
    { char: '😶', names: ['no_mouth', 'silent'] },
    { char: '😏', names: ['smirk', 'flirt'] },
    { char: '😒', names: ['unamused', 'meh', 'bore'] },
    { char: '🙄', names: ['roll_eyes', 'saracasm'] },
    { char: '😬', names: ['grimacing', 'awkward'] },
    { char: '🤥', names: ['lying_face', 'liar'] },
    { char: '😌', names: ['relieved', 'whew'] },
    { char: '😔', names: ['pensive', 'sad'] },
    { char: '😪', names: ['sleepy', 'tired'] },
    { char: '🤤', names: ['drooling_face'] },
    { char: '😴', names: ['sleeping', 'zzz'] },
    { char: '😷', names: ['mask', 'sick'] },
    { char: '🤒', names: ['thermometer_face', 'sick'] },
    { char: '🤕', names: ['head_bandage', 'hurt'] },
    { char: '🤢', names: ['nauseated', 'vomit', 'sick'] },
    { char: '🤮', names: ['vomiting', 'sick'] },
    { char: '🤧', names: ['sneezing_face', 'sick'] },
    { char: '🥵', names: ['hot_face', 'heat'] },
    { char: '🥶', names: ['cold_face', 'freezing'] },
    { char: '🥴', names: ['woozy_face', 'drunk'] },
    { char: '😵', names: ['dizzy_face'] },
    { char: '🤯', names: ['exploding_head', 'mind_blown'] },
    { char: '🤠', names: ['cowboy_hat_face'] },
    { char: '🥳', names: ['partying_face', 'celebration'] },
    { char: '😎', names: ['sunglasses', 'cool'] },
    { char: '🤓', names: ['nerd_face', 'geek'] },
    { char: '🧐', names: ['monocle_face'] },
    { char: '😕', names: ['confused'] },
    { char: '😟', names: ['worried'] },
    { char: '🙁', names: ['slightly_frowning_face'] },
    { char: '😮', names: ['open_mouth', 'surprise'] },
    { char: '😯', names: ['hushed', 'quiet'] },
    { char: '😲', names: ['astonished', 'shock'] },
    { char: '😳', names: ['flushed'] },
    { char: '🥺', names: ['pleading_face', 'puppy'] },
    { char: '😦', names: ['frowning_open_mouth'] },
    { char: '😧', names: ['anguished'] },
    { char: '😨', names: ['fearful', 'scared'] },
    { char: '😰', names: ['cold_sweat', 'nervous'] },
    { char: '😥', names: ['disappointed_relieved_face', 'phew'] },
    { char: '😢', names: ['cry', 'sad', 'tear'] },
    { char: '😭', names: ['sob', 'sad', 'cry'] },
    { char: '😱', names: ['scream', 'scared'] },
    { char: '😖', names: ['confounded'] },
    { char: '😣', names: ['persevere'] },
    { char: '😞', names: ['disappointed', 'sad'] },
    { char: '😓', names: ['sweat', 'hot'] },
    { char: '😩', names: ['weary', 'tired'] },
    { char: '😫', names: ['tired_face'] },
    { char: '🥱', names: ['yawning_face', 'tired'] },
    { char: '😤', names: ['triumph', 'steam'] },
    { char: '😡', names: ['pout', 'rage', 'angry'] },
    { char: '😠', names: ['angry'] },
    { char: '🤬', names: ['cursing_face', 'foul'] },
    { char: '😈', names: ['smiling_imp', 'devil', 'evil'] },
    { char: '👿', names: ['imp', 'devil'] },
    { char: '💀', names: ['skull', 'dead'] },
    { char: '☠️', names: ['skull_and_crossbones', 'danger', 'pirate'] },
    { char: '💩', names: ['hankey', 'poop', 'shit'] },
    { char: '🤡', names: ['clown_face'] },
    { char: '👹', names: ['japanese_ogre', 'monster'] },
    { char: '👺', names: ['japanese_goblin'] },
    { char: '👻', names: ['ghost', 'halloween'] },
    { char: '👽', names: ['alien', 'ufo'] },
    { char: '👾', names: ['alien_monster', 'game'] },
    { char: '🤖', names: ['robot'] },
    { char: '😺', names: ['smiley_cat'] },
    { char: '😸', names: ['smile_cat'] },
    { char: '😹', names: ['joy_cat'] },
    { char: '😻', names: ['heart_eyes_cat'] },
    { char: '😼', names: ['smirk_cat'] },
    { char: '😽', names: ['kissing_cat'] },
    { char: '🙀', names: ['scream_cat'] },
    { char: '😿', names: ['crying_cat_face'] },
    { char: '😾', names: ['pouting_cat'] },
    { char: '🙈', names: ['see_no_evil', 'monkey'] },
    { char: '🙉', names: ['hear_no_evil', 'monkey'] },
    { char: '🙊', names: ['speak_no_evil', 'monkey'] },
    { char: '❤️', names: ['heart', 'love'] },
    { char: '🧡', names: ['orange_heart'] },
    { char: '💛', names: ['yellow_heart'] },
    { char: '💚', names: ['green_heart'] },
    { char: '💙', names: ['blue_heart'] },
    { char: '💜', names: ['purple_heart'] },
    { char: '🖤', names: ['black_heart'] },
    { char: '🤍', names: ['white_heart'] },
    { char: '🤎', names: ['brown_heart'] },
    { char: '💔', names: ['broken_heart'] },
    { char: '🔥', names: ['fire', 'hot', 'lit'] },
    { char: '✨', names: ['sparkles', 'magic'] },
    { char: '🌟', names: ['star'] },
    { char: '💯', names: ['100', 'score'] },
    { char: '💥', names: ['boom', 'collision'] },
    { char: '💢', names: ['anger'] },
    { char: '💦', names: ['sweat_drops', 'water'] },
    { char: '💤', names: ['zzz', 'sleep'] },
    { char: '👋', names: ['wave', 'hello', 'bye'] },
    { char: '🤚', names: ['raised_back_of_hand'] },
    { char: '🖐️', names: ['raised_hand_with_fingers_splayed'] },
    { char: '✋', names: ['raised_hand', 'stop', 'high_five'] },
    { char: '🖖', names: ['vulcan_salute'] },
    { char: '👌', names: ['ok_hand'] },
    { char: '🤏', names: ['pinching_hand', 'tiny'] },
    { char: '✌️', names: ['v', 'peace'] },
    { char: '🤞', names: ['crossed_fingers', 'luck'] },
    { char: '🤟', names: ['love_you_gesture'] },
    { char: '🤘', names: ['sign_of_the_horns', 'rock'] },
    { char: '🤙', names: ['call_me_hand'] },
    { char: '👈', names: ['point_left'] },
    { char: '👉', names: ['point_right'] },
    { char: '👆', names: ['point_up'] },
    { char: '🖕', names: ['middle_finger', 'fu'] },
    { char: '👇', names: ['point_down'] },
    { char: '☝️', names: ['point_up_2'] },
    { char: '👍', names: ['thumbsup', 'like'] },
    { char: '👎', names: ['thumbsdown', 'dislike'] },
    { char: '✊', names: ['fist'] },
    { char: '👊', names: ['facepunch', 'punch'] },
    { char: '🤛', names: ['left_facing_fist'] },
    { char: '🤜', names: ['right_facing_fist'] },
    { char: '👏', names: ['clap', 'applause'] },
    { char: '🙌', names: ['raised_hands', 'hooray'] },
    { char: '👐', names: ['open_hands'] },
    { char: '🤲', names: ['palms_up_together'] },
    { char: '🤝', names: ['handshake', 'deal'] },
    { char: '🙏', names: ['pray', 'please', 'thanks'] }
];

const gifList = [
    { url: 'https://media.giphy.com/media/3o7TKSjRrfIPjeiVyM/giphy.gif', keywords: ['loading', 'spinner', 'wait'] },
    { url: 'https://media.giphy.com/media/l0HlHJGHe3yAMhdQY/giphy.gif', keywords: ['thumbs up', 'like', 'agree', 'yes'] },
    { url: 'https://media.giphy.com/media/GeimqsH0TLDt4tScGw/giphy.gif', keywords: ['cat', 'jam', 'dance', 'party'] },
    { url: 'https://media.giphy.com/media/xT9IgIc0lryrxuqVH2/giphy.gif', keywords: ['error', 'glitch', 'bug', 'broken'] },
    { url: 'https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif', keywords: ['coding', 'hacker', 'computer', 'dev'] },
    { url: 'https://media.giphy.com/media/YQitE4YNQNahy/giphy.gif', keywords: ['hacker', 'matrix', 'code'] },
    { url: 'https://media.giphy.com/media/mokQK7oyiR8Sk/giphy.gif', keywords: ['dog', 'funny', 'animal'] },
    { url: 'https://media.giphy.com/media/l3V0lsGtTMSB5YNgc/giphy.gif', keywords: ['dance', 'party', 'fun'] }
];
